name: SPA CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubutnu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - run: yarn install
    - run: yarn run llint
    - run: yarn run test
    - run: yarn build
