name: deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be deployed'
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          always-auth: true
          registry-url: https://npm.pkg.github.com
      - run: npm pack @rbelmega/crypto-trade-2@${{ github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: tar -xvzf rbelmega-crypto-trade-2-${{ github.event.inputs.tag }}.tgz

      - name: Remove from S3
        uses: vitorsgomes/s3-rm-action@master
        with:
          args: --recursive
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_REGION: ${{ secrets.S3_BUCKET_REGION }}

      - name: Deploying to S3
        uses: reggionick/s3-deploy@v3
        with:
          folder: package
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          private: true
          no-cache: true
