name: deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be deployed'
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          always-auth: true
          registry-url: https://npm.pkg.github.com
      - run: npm pack @rbelmega/crypto-trade-2@${{ github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Unzipping
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq rbelmega-crypto-trade-2-${{ github.event.inputs.tag }}.tgz -d build

      - name: Deploying to S3
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          private: true
